name: Build and Push to git.beans.team

on:
  push:
    branches:
      - main

jobs:
  update-registry:
    name: Update Registry Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to git.beans.team
        uses: docker/login-action@v3
        with:
          registry: git.beans.team
          username: em
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and Push Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: git.beans.team/em/scouter:latest
